interface PageCaptionTrack { baseUrl: string; languageCode: string; kind?: string }
interface PagePlayerResponse { captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: PageCaptionTrack[] } } }
interface YouTubePlayerElement extends Element { getPlayerResponse?: () => PagePlayerResponse }
interface YouTubeConfig { get?: (key: string) => unknown; data_?: Record<string, unknown> }
interface TranscriptSegment { id: string; startMs: number; endMs: number; sourceText: string }
type CaptionPayload = { text: string; format: "json3" | "xml" | "segments"; source: string };

declare global {
  interface Window {
    ytInitialPlayerResponse?: PagePlayerResponse;
    ytInitialData?: unknown;
    ytplayer?: { config?: { args?: { player_response?: string } } };
    ytcfg?: YouTubeConfig;
  }
}

function playerResponse(): PagePlayerResponse | undefined {
  const player = document.querySelector<YouTubePlayerElement>("#movie_player, ytd-player");
  try {
    const response = player?.getPlayerResponse?.();
    if (response) return response;
  } catch { /* Thử nguồn tiếp theo. */ }
  if (window.ytInitialPlayerResponse) return window.ytInitialPlayerResponse;
  const serialized = window.ytplayer?.config?.args?.player_response;
  if (serialized) {
    try { return JSON.parse(serialized) as PagePlayerResponse; }
    catch { return undefined; }
  }
  return undefined;
}

function configValue(key: string): unknown {
  try { return window.ytcfg?.get?.(key) ?? window.ytcfg?.data_?.[key]; }
  catch { return window.ytcfg?.data_?.[key]; }
}

interface TranscriptCommand { params: string; clickTrackingParams?: string }

function findTranscriptCommand(value: unknown, seen = new Set<object>()): TranscriptCommand | undefined {
  if (!value || typeof value !== "object" || seen.has(value)) return undefined;
  seen.add(value);
  const object = value as Record<string, unknown>;
  const endpoint = object.getTranscriptEndpoint as { params?: unknown } | undefined;
  if (typeof endpoint?.params === "string") {
    return typeof object.clickTrackingParams === "string"
      ? { params: endpoint.params, clickTrackingParams: object.clickTrackingParams }
      : { params: endpoint.params };
  }
  for (const child of Object.values(object)) {
    const result = findTranscriptCommand(child, seen);
    if (result) return result;
  }
  return undefined;
}

function collectTranscriptSegments(value: unknown, output: TranscriptSegment[], seen = new Set<object>()): void {
  if (!value || typeof value !== "object" || seen.has(value)) return;
  seen.add(value);
  const object = value as Record<string, unknown>;
  const renderer = object.transcriptSegmentRenderer as Record<string, unknown> | undefined;
  if (renderer) {
    const snippet = renderer.snippet as { runs?: Array<{ text?: string }>; simpleText?: string } | undefined;
    const startMs = Number(renderer.startMs);
    const endMs = Number(renderer.endMs);
    const sourceText = (snippet?.runs?.map((run) => run.text ?? "").join("") ?? snippet?.simpleText ?? "").replace(/\s+/g, " ").trim();
    if (Number.isFinite(startMs) && sourceText) {
      output.push({ id: String(renderer.cueGroupId ?? `${startMs}-${output.length}`), startMs, endMs: Number.isFinite(endMs) && endMs > startMs ? endMs : startMs + 2000, sourceText });
    }
  }
  const cueRenderer = object.transcriptCueRenderer as Record<string, unknown> | undefined;
  if (cueRenderer) {
    const cue = cueRenderer.cue as { runs?: Array<{ text?: string }>; simpleText?: string } | undefined;
    const startMs = Number(cueRenderer.startOffsetMs);
    const durationMs = Number(cueRenderer.durationMs);
    const sourceText = (cue?.runs?.map((run) => run.text ?? "").join("") ?? cue?.simpleText ?? "").replace(/\s+/g, " ").trim();
    if (Number.isFinite(startMs) && sourceText) {
      output.push({ id: `cue-${startMs}-${output.length}`, startMs, endMs: startMs + (Number.isFinite(durationMs) && durationMs > 0 ? durationMs : 2000), sourceText });
    }
  }
  for (const child of Object.values(object)) collectTranscriptSegments(child, output, seen);
}

function protobufString(field: number, value: string): number[] {
  const bytes = [...new TextEncoder().encode(value)];
  return [(field << 3) | 2, bytes.length, ...bytes];
}

function generatedTranscriptParams(videoId: string, languageCode: string, autoGenerated: boolean): string {
  const inner = [
    ...protobufString(1, autoGenerated ? "asr" : ""),
    ...protobufString(2, languageCode),
    ...protobufString(3, ""),
  ];
  const bytes = [
    ...protobufString(1, videoId),
    (2 << 3) | 2, inner.length, ...inner,
    (3 << 3), 1,
    ...protobufString(5, "engagement-panel-searchable-transcript-search-panel"),
    (6 << 3), 1, (7 << 3), 1, (8 << 3), 1,
  ];
  const base64 = btoa(String.fromCharCode(...bytes)).replace(/\+/g, "-").replace(/\//g, "_");
  return encodeURIComponent(base64);
}

async function transcriptPayload(track?: PageCaptionTrack): Promise<CaptionPayload> {
  const apiKey = configValue("INNERTUBE_API_KEY");
  const context = configValue("INNERTUBE_CONTEXT");
  if (typeof apiKey !== "string" || !context || typeof context !== "object") throw new Error("YouTube chưa cung cấp cấu hình transcript");

  const clientName = configValue("INNERTUBE_CLIENT_NAME");
  const clientVersion = configValue("INNERTUBE_CLIENT_VERSION");
  const visitorData = configValue("VISITOR_DATA");
  const headers: Record<string, string> = { "content-type": "application/json; charset=UTF-8", "x-goog-api-format-version": "2" };
  if (typeof clientName === "string" || typeof clientName === "number") headers["x-youtube-client-name"] = String(clientName);
  if (typeof clientVersion === "string") headers["x-youtube-client-version"] = clientVersion;
  if (typeof visitorData === "string") headers["x-goog-visitor-id"] = visitorData;

  const videoId = new URL(location.href).searchParams.get("v");
  if (!videoId) throw new Error("Không xác định được video YouTube");
  const watchData = (document.querySelector("ytd-watch-flexy") as (Element & { data?: unknown }) | null)?.data;
  const pageCommand = findTranscriptCommand(watchData) ?? findTranscriptCommand(window.ytInitialData);
  const params = track
    ? generatedTranscriptParams(videoId, track.languageCode, track.kind === "asr")
    : pageCommand?.params;
  if (!params) throw new Error("Video không cung cấp transcript");
  const requestContext = structuredClone(context) as Record<string, unknown>;
  if (pageCommand?.clickTrackingParams) requestContext.clickTracking = { clickTrackingParams: pageCommand.clickTrackingParams };

  const transcriptResponse = await fetch(`/youtubei/v1/get_transcript?key=${encodeURIComponent(apiKey)}&prettyPrint=false`, {
    method: "POST", credentials: "include", headers, body: JSON.stringify({ context: requestContext, params }),
  });
  if (!transcriptResponse.ok) {
    const detail = (await transcriptResponse.text()).slice(0, 300).replace(/\s+/g, " ").trim();
    throw new Error(`YouTube transcript trả HTTP ${transcriptResponse.status}${detail ? `: ${detail}` : ""}`);
  }
  const segments: TranscriptSegment[] = [];
  collectTranscriptSegments(await transcriptResponse.json(), segments);
  if (!segments.length) throw new Error("Transcript YouTube không có nội dung");
  return { text: JSON.stringify({ segments }), format: "segments", source: "YouTube transcript" };
}

async function captionPayload(): Promise<CaptionPayload> {
  let response: PagePlayerResponse | undefined;
  for (let attempt = 0; attempt < 20 && !response; attempt += 1) {
    response = playerResponse();
    if (!response) await new Promise((resolve) => setTimeout(resolve, 250));
  }
  const tracks = response?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  const track = tracks.find((item) => item.languageCode === "vi") ?? tracks.find((item) => item.kind !== "asr") ?? tracks[0];
  if (!track?.baseUrl.startsWith("https://www.youtube.com/api/timedtext")) return transcriptPayload(track);
  const source = track.kind === "asr" ? "YouTube (tự động)" : "YouTube";

  const jsonUrl = new URL(track.baseUrl);
  jsonUrl.searchParams.set("fmt", "json3");
  const jsonResponse = await fetch(jsonUrl, { credentials: "include" });
  const jsonText = jsonResponse.ok ? await jsonResponse.text() : "";
  if (jsonText.trim().startsWith("{")) return { text: jsonText, format: "json3", source };

  const xmlUrl = new URL(track.baseUrl);
  xmlUrl.searchParams.delete("fmt");
  const xmlResponse = await fetch(xmlUrl, { credentials: "include" });
  const xmlText = xmlResponse.ok ? await xmlResponse.text() : "";
  if (xmlText.trim().startsWith("<")) return { text: xmlText, format: "xml", source };
  return transcriptPayload(track);
}

window.addEventListener("message", (event: MessageEvent<unknown>) => {
  if (event.source !== window || location.hostname !== "www.youtube.com") return;
  const request = event.data as { type?: string; requestId?: string } | null;
  if (request?.type !== "PXH_CAPTIONS_REQUEST" || typeof request.requestId !== "string") return;
  void captionPayload().then(
    (payload) => window.postMessage({ type: "PXH_CAPTIONS_RESPONSE", requestId: request.requestId, payload }, location.origin),
    (error: unknown) => window.postMessage({ type: "PXH_CAPTIONS_RESPONSE", requestId: request.requestId, error: error instanceof Error ? error.message : "Không thể tải phụ đề" }, location.origin),
  );
});

export {};
